# Generated by Django 3.0.3 on 2020-04-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('VU', 'đã vote up'), ('VD', 'đã vote down'), ('A', 'đã trả lời'), ('AC', 'cũng đã trả lời'), ('C', 'đã bình luận trả lời'), ('AA', 'đã đánh dấu trả lời'), ('S', 'đã lưu')], max_length=2),
        ),
    ]
