# Generated by Django 3.0.3 on 2020-04-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200412_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='content',
        ),
        migrations.AlterField(
            model_name='action',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
