# Generated by Django 3.0.3 on 2020-04-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200410_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
