# Generated by Django 3.0.3 on 2020-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200411_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.BooleanField(default=True),
        ),
    ]
