# Generated by Django 3.0.3 on 2020-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
