# Generated by Django 3.0.3 on 2020-04-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0003_auto_20200410_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qanda.Answer'),
        ),
    ]
