# Generated by Django 3.0.3 on 2020-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0007_auto_20200411_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_reply',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
